### ISSUE TITLE
CDN for coreui-icons.min.css has changed

### ISSUE THREAD

**Issue by japc-74** [InfyOmLabs/coreui-templates#29]
https://unpkg.com/@coreui/icons/css/coreui-icons.min.css is not longer available

**Comment by mitulgolakiya** [comment]
@japc-74 yes, I just faced this issue yesterday and going to it fix it soon.

**Comment by sooviet** [comment]
After this change, my admin portal design breaks. What is the issue with coreui? I generated the template with infyom. Is anybody having the same issues as me?

**Comment by ajayinfyom** [comment]
@sooviet I think now your problem was resolved.
if you getting still a problem then you need to publish layout again.
