### ISSUE TITLE
Localization not done properly for auth and user

### ISSUE THREAD

**Issue by skys215** [InfyOmLabs/coreui-templates#32]
I found out that there are many _locale.stub didn't use @lang function to get the localized strings. 
The file is listed below if necessary:
- [templates/scaffold/auth/email_locale.stub#L8](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/auth/email_locale.stub#L8)
- [templates/scaffold/auth/login_locale.stub#L8](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/auth/login_locale.stub#L8)
- [templates/scaffold/auth/register_locale.stub#L8](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/auth/register_locale.stub#L8)
- [templates/scaffold/auth/reset_locale.stub#L8](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/auth/reset_locale.stub#L8)
- [templates/scaffold/users/create.stub#L6](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/users/create.stub#L6)
- [templates/scaffold/users/create.stub#L8](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/users/create.stub#L8)
- [templates/scaffold/users/edit.stub#L6](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/users/edit.stub#L6)
- [templates/scaffold/users/edit.stub#L8](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/users/edit.stub#L8)
- all the field names in [templates/scaffold/users/fields.stub](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/users/fields.stub)
- [templates/scaffold/users/index.stub#L5](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/users/index.stub#L5)
- [templates/scaffold/users/menu.stub#L4](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/users/menu.stub#L4)
- [templates/scaffold/users/show.stub#L6](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/users/show.stub#L6)
- [templates/scaffold/users/show.stub#L8](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/users/show.stub#L8)
- [templates/scaffold/users/show.stub#L18](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/users/show.stub#L18)
- all the field names in [templates/scaffold/users/show_fields.stub](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/users/show_fields.stub)
- table heads [templates/scaffold/users/table.stub#L4](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/users/table.stub#L4)
- and [templates/scaffold/users/table.stub#L20](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/users/table.stub#L20)
- [templates/scaffold/users/table.stub#L20](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/users/table.stub#L20)
- the "Edit" [templates/scaffold/views/edit_locale.stub#L18](https://github.com/InfyOmLabs/coreui-templates/tree/f9127fa160e1578e092badd708bf130c03605a52/templates/scaffold/views/edit_locale.stub#L18)

One more thing, I assume that there is missing some locale stub, such as :
- verify.stub

**Comment by ShaileshInfyom** [comment]
This issue has been fixed in PR https://github.com/InfyOmLabs/coreui-templates/pull/46
