### ISSUE TITLE
For select input a placeholder should be used

### ISSUE THREAD

**Issue by aydinbulut** [InfyOmLabs/coreui-templates#37]
This is generated:
`{!! Form::select('user_id', $userItems, null, ['class' => 'form-control']) !!}`

In could be like this instead:
`{!! Form::select('user_id', $userItems, null, ['class' => 'form-control', 'placeholder' => 'Pick a user...']) !!}`

The only change is adding a placeholder to the 4rt argument.
`'placeholder' => 'Pick a user...'`

**Comment by ShaileshInfyom** [comment]
@aydinbulut this issue done in PR https://github.com/InfyOmLabs/coreui-templates/pull/38  Feel free to re-open the issue with more details if you are still facing this issue.
